import {useEffect,useMemo,useState} from 'react'
import * as XLSX from 'xlsx'
import {supabase} from './lib/supabase'

function csvParse(text:string){
 const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[]}else cell+=c}
 if(cell||row.length){row.push(cell);if(row.some(v=>v.trim()))rows.push(row)}
 return rows
}
function download(name:string,content:string,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function excelHtml(name:string,headers:string[],rows:any[][]){const body=rows.map(r=>'<tr>'+r.map(v=>'<td>'+String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')+'</td>').join('')+'</tr>').join('');const html='<html><head><meta charset="utf-8"></head><body><table><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr>'+body+'</table></body></html>';download(name,html,'application/vnd.ms-excel')}
function printHtml(title:string,body:string){const w=window.open('','_blank','width=900,height=700');if(!w)return;w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+title+'</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#172033}h1{margin:0 0 8px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #ccd3df;padding:8px;text-align:left}@media print{button{display:none}}</style></head><body>'+body+'<script>window.onload=()=>window.print()<\\/script></body></html>');w.document.close()}
async function institutionId(){const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)return null;const {data}=await supabase.from('profiles').select('institution_id').eq('id',uid).single();return data?.institution_id??null}

export function ReportsEnhancedPage({setError}:{setError:(s:string)=>void}){
 const [templates,setTemplates]=useState<any[]>([]),[name,setName]=useState(''),[type,setType]=useState('custom'),[fields,setFields]=useState('Name, Admission No, Class, Section'),[busy,setBusy]=useState(false)
 async function load(){const {data,error}=await supabase.from('report_templates').select('id,name,report_type,active,config').order('created_at',{ascending:false});if(error)setError(error.message);else setTemplates(data??[])}
 useEffect(()=>{load()},[])
 async function add(e:React.FormEvent){e.preventDefault();const id=await institutionId();if(!id)return;setBusy(true);const {error}=await supabase.from('report_templates').insert({institution_id:id,name,report_type:type,config:{fields:fields.split(',').map(x=>x.trim()).filter(Boolean),version:1}});if(error)setError(error.message);else{setName('');await load()}setBusy(false)}
 const rows=templates.map(x=>[x.name,x.report_type,x.active?'Yes':'No',(x.config?.fields??[]).join(' | ')])
 return <section className="panel"><div className="section-head"><div><p className="eyebrow">Reports</p><h3>Report Builder & Documents</h3></div><div className="tabs"><button className="ghost small" onClick={()=>excelHtml('report-templates.xls',['Name','Type','Active','Fields'],rows)}>Excel</button><button className="ghost small" onClick={()=>download('report-templates.csv','Name,Type,Active,Fields\n'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}>CSV</button><button className="ghost small" onClick={()=>printHtml('Bab Ul Ilm Report Templates','<h1>Bab Ul Ilm — Report Templates</h1><p>Generated '+new Date().toLocaleString()+'</p><table><tr><th>Name</th><th>Type</th><th>Active</th><th>Fields</th></tr>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+String(v??'')+'</td>').join('')+'</tr>').join('')+'</table>')}>Print / PDF</button></div></div><form className="inline-form" onSubmit={add}><input placeholder="Report name" value={name} onChange={e=>setName(e.target.value)} required/><select value={type} onChange={e=>setType(e.target.value)}>{['progress','attendance','fee','staff','custom'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Fields, comma separated" value={fields} onChange={e=>setFields(e.target.value)} required/><button className="primary small" disabled={busy}>{busy?'Saving…':'Save template'}</button></form><div className="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Active</th><th>Configured fields</th></tr></thead><tbody>{rows.map((r,i)=><tr key={templates[i].id}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="muted empty-small">No templates yet.</p>}</div></section>
}

export function HrPayrollPage({setError}:{setError:(s:string)=>void}){
 const [staff,setStaff]=useState<any[]>([]),[pay,setPay]=useState<any[]>([]),[form,setForm]=useState({staff_id:'',pay_period:new Date().toISOString().slice(0,10),basic:'',allowances:'0',deductions:'0'}),[busy,setBusy]=useState(false)
 async function load(){const id=await institutionId();if(!id)return;const [s,p]=await Promise.all([supabase.from('staff').select('id,employee_no,first_name,last_name,designation,status').eq('institution_id',id).order('first_name'),supabase.from('staff_payroll').select('id,staff_id,pay_period,basic,allowances,deductions,net_pay,status,payment_method,reference_no,paid_on').eq('institution_id',id).order('pay_period',{ascending:false})]);[s,p].forEach(q=>{if(q.error)setError(q.error.message)});setStaff(s.data??[]);setPay(p.data??[])}
 useEffect(()=>{load()},[])
 async function save(e:React.FormEvent){e.preventDefault();const id=await institutionId();if(!id)return;setBusy(true);const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('staff_payroll').upsert({institution_id:id,staff_id:form.staff_id,pay_period:form.pay_period,basic:Number(form.basic||0),allowances:Number(form.allowances||0),deductions:Number(form.deductions||0),created_by:u.user?.id},{onConflict:'institution_id,staff_id,pay_period'});if(error)setError(error.message);else{setForm({...form,basic:'',allowances:'0',deductions:'0'});await load()}setBusy(false)}
 async function mark(id:string,status:string){const {error}=await supabase.from('staff_payroll').update({status,...(status==='paid'?{paid_on:new Date().toISOString().slice(0,10)}:{})}).eq('id',id);if(error)setError(error.message);else load()}
 const total=useMemo(()=>pay.reduce((n,x)=>n+Number(x.net_pay||0),0),[pay])
 const rows=pay.map(x=>{const s=staff.find(v=>v.id===x.staff_id);return [s?.employee_no||'',(s?.first_name||'')+' '+(s?.last_name||''),x.pay_period,x.basic,x.allowances,x.deductions,x.net_pay,x.status]})
 return <section className="panel"><div className="section-head"><div><p className="eyebrow">HR & Payroll</p><h3>Payroll register</h3></div><strong>Net total: ₹{total.toLocaleString('en-IN',{minimumFractionDigits:2})}</strong></div><form className="inline-form" onSubmit={save}><select value={form.staff_id} onChange={e=>setForm({...form,staff_id:e.target.value})} required><option value="">Select staff</option>{staff.map(s=><option key={s.id} value={s.id}>{s.employee_no} · {s.first_name} {s.last_name||''}</option>)}</select><input type="date" value={form.pay_period} onChange={e=>setForm({...form,pay_period:e.target.value})} required/><input type="number" min="0" step="0.01" placeholder="Basic" value={form.basic} onChange={e=>setForm({...form,basic:e.target.value})} required/><input type="number" min="0" step="0.01" placeholder="Allowances" value={form.allowances} onChange={e=>setForm({...form,allowances:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Deductions" value={form.deductions} onChange={e=>setForm({...form,deductions:e.target.value})}/><button className="primary small" disabled={busy}>{busy?'Saving…':'Save payroll'}</button></form><div className="tabs"><button className="ghost small" onClick={()=>excelHtml('payroll.xls',['Employee','Staff','Period','Basic','Allowances','Deductions','Net','Status'],rows)}>Excel</button><button className="ghost small" onClick={()=>printHtml('Bab Ul Ilm Payroll','<h1>Bab Ul Ilm — Payroll</h1><table><tr><th>Employee</th><th>Staff</th><th>Period</th><th>Basic</th><th>Allowances</th><th>Deductions</th><th>Net</th><th>Status</th></tr>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+String(v??'')+'</td>').join('')+'</tr>').join('')+'</table>')}>Print / PDF</button></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Staff</th><th>Period</th><th>Basic</th><th>Allow.</th><th>Ded.</th><th>Net</th><th>Status</th><th>Action</th></tr></thead><tbody>{pay.map(x=>{const s=staff.find(v=>v.id===x.staff_id);return <tr key={x.id}><td>{s?.employee_no}</td><td>{s?.first_name} {s?.last_name||''}</td><td>{x.pay_period}</td><td>₹{Number(x.basic).toFixed(2)}</td><td>₹{Number(x.allowances).toFixed(2)}</td><td>₹{Number(x.deductions).toFixed(2)}</td><td><strong>₹{Number(x.net_pay).toFixed(2)}</strong></td><td>{x.status}</td><td>{x.status==='draft'&&<button className="secondary small" onClick={()=>mark(x.id,'approved')}>Approve</button>} {x.status==='approved'&&<button className="secondary small" onClick={()=>mark(x.id,'paid')}>Mark paid</button>}</td></tr>})}</tbody></table>{!pay.length&&<p className="muted empty-small">No payroll records.</p>}</div></section>
}

export function DataImportPromotionPage({setError}:{setError:(s:string)=>void}){
 const [students,setStudents]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[toClass,setToClass]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const id=await institutionId();if(!id)return;const [s,c]=await Promise.all([supabase.from('students').select('id,admission_no,first_name,last_name,class_id,status').eq('institution_id',id).eq('status','active').order('first_name'),supabase.from('academic_classes').select('id,name,code').eq('institution_id',id).eq('active',true).order('level_order')]);[s,c].forEach(q=>{if(q.error)setError(q.error.message)});setStudents(s.data??[]);setClasses(c.data??[])}
 useEffect(()=>{load()},[])
 async function importFile(file:File){setBusy(true);setMessage('');try{let rows:string[][];if(/\\.(xlsx|xls)$/i.test(file.name)){const buffer=await file.arrayBuffer();const wb=XLSX.read(buffer,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];if(!ws)throw new Error('Excel workbook has no worksheets');const data=XLSX.utils.sheet_to_json<any[]>(ws,{header:1,defval:''});rows=data.map(r=>r.map(v=>String(v??'')));}else{rows=csvParse(await file.text())}if(rows.length<2)throw new Error('Import file is empty');const headers=rows[0].map(x=>x.trim().toLowerCase());const idx=(n:string)=>headers.indexOf(n);const idAdmission=idx('admission_no'),idFirst=idx('first_name');if(idAdmission<0||idFirst<0)throw new Error('Import requires admission_no and first_name columns');const institution_id=await institutionId();if(!institution_id)throw new Error('Institution not found');const payload=rows.slice(1).filter(r=>r[idAdmission]&&r[idFirst]).map(r=>({institution_id,admission_no:r[idAdmission],roll_no:r[idx('roll_no')]||null,first_name:r[idFirst],middle_name:r[idx('middle_name')]||null,last_name:r[idx('last_name')]||null,gender:r[idx('gender')]||null,date_of_birth:r[idx('date_of_birth')]||null,phone:r[idx('phone')]||null,email:r[idx('email')]||null,guardian_name:r[idx('guardian_name')]||null,guardian_phone:r[idx('guardian_phone')]||null,status:r[idx('status')]||'active',joined_on:r[idx('joined_on')]||null,notes:r[idx('notes')]||null}));if(!payload.length)throw new Error('No valid student rows found');const {error}=await supabase.from('students').upsert(payload,{onConflict:'institution_id,admission_no'});if(error)throw error;setMessage('Imported '+payload.length+' student records successfully.');await load()}catch(e:any){setError(e?.message||'Import failed')}setBusy(false)}
 async function promote(){if(!selected.length||!toClass)return;setBusy(true);const id=await institutionId();const {data:u}=await supabase.auth.getUser();const academic_year_id=(await supabase.from('academic_years').select('id').eq('institution_id',id).order('start_date',{ascending:false}).limit(1).maybeSingle()).data?.id;if(!id||!academic_year_id){setError('Institution or academic year not found');setBusy(false);return}for(const student_id of selected){const from=(students.find(s=>s.id===student_id)?.class_id)||null;const {error}=await supabase.from('student_promotions').insert({institution_id:id,student_id,from_class_id:from,to_class_id:toClass,academic_year_id,decision:'promoted',decided_on:new Date().toISOString().slice(0,10),decided_by:u.user?.id});if(error){setError(error.message);setBusy(false);return}const {error:ue}=await supabase.from('students').update({class_id:toClass,academic_year_id}).eq('id',student_id);if(ue){setError(ue.message);setBusy(false);return}}setMessage('Promotion completed for '+selected.length+' student(s).');setSelected([]);await load();setBusy(false)}
 const allSelected=students.length>0&&selected.length===students.length
 return <section className="panel"><div className="section-head"><div><p className="eyebrow">Data tools</p><h3>Bulk Import & Promotion Wizard</h3></div><label className="ghost small">{busy?'Working…':'Import CSV / Excel'}<input type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" hidden onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label></div><p className="muted">CSV / Excel columns: admission_no, first_name, last_name, roll_no, gender, date_of_birth, phone, email, guardian_name, guardian_phone, status, joined_on, notes.</p>{message&&<div className="success banner">{message}</div>}<div className="section-head"><div><p className="eyebrow">Promotion</p><h3>Select active students</h3></div><select value={toClass} onChange={e=>setToClass(e.target.value)}><option value="">Target class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary small" disabled={busy||!selected.length||!toClass} onClick={promote}>Promote selected</button></div><div className="table-wrap"><table><thead><tr><th><input type="checkbox" checked={allSelected} onChange={e=>setSelected(e.target.checked?students.map(s=>s.id):[])}/></th><th>Admission</th><th>Name</th><th>Current class</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,s.id]:v.filter(x=>x!==s.id))}/></td><td>{s.admission_no}</td><td>{s.first_name} {s.last_name||''}</td><td>{classes.find(c=>c.id===s.class_id)?.name||'—'}</td></tr>)}</tbody></table>{!students.length&&<p className="muted empty-small">No active students.</p>}</div></section>
}
