-- Bab UL Ilm foundation schema
create schema if not exists app_private;

create table if not exists public.institutions (
  id uuid primary key default gen_random_uuid(), name text not null, legal_name text, slug text not null unique,
  logo_path text, default_language text not null default 'en' check (default_language in ('en','ur')),
  timezone text not null default 'Asia/Kolkata', currency text not null default 'INR',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.branches (
  id uuid primary key default gen_random_uuid(), institution_id uuid not null references public.institutions(id) on delete cascade,
  name text not null, code text not null, address jsonb not null default '{}'::jsonb, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(institution_id,code)
);
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade, institution_id uuid references public.institutions(id) on delete set null,
  display_name text, phone text, avatar_path text, locale text not null default 'en' check(locale in ('en','ur')),
  theme text not null default 'system' check(theme in ('light','dark','system')), must_change_password boolean not null default false,
  disabled_at timestamptz, last_login_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(), institution_id uuid references public.institutions(id) on delete cascade,
  name text not null, slug text not null, description text, is_system boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(institution_id,slug)
);
create table if not exists public.permissions (
  id uuid primary key default gen_random_uuid(), key text not null unique, description text not null, module text not null, created_at timestamptz not null default now()
);
create table if not exists public.role_permissions (
  role_id uuid not null references public.roles(id) on delete cascade, permission_id uuid not null references public.permissions(id) on delete cascade,
  created_at timestamptz not null default now(), primary key(role_id,permission_id)
);
create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade, role_id uuid not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(), primary key(user_id,role_id)
);
create table if not exists public.user_branches (
  user_id uuid not null references auth.users(id) on delete cascade, branch_id uuid not null references public.branches(id) on delete cascade,
  created_at timestamptz not null default now(), primary key(user_id,branch_id)
);
create table if not exists public.app_settings (
  id uuid primary key default gen_random_uuid(), institution_id uuid not null references public.institutions(id) on delete cascade,
  key text not null, value jsonb not null default '{}'::jsonb, updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(), unique(institution_id,key)
);
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key, institution_id uuid references public.institutions(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null, action text not null, entity_type text, entity_id text,
  branch_id uuid references public.branches(id) on delete set null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.academic_years (
  id uuid primary key default gen_random_uuid(), institution_id uuid not null references public.institutions(id) on delete cascade,
  name text not null, starts_on date not null, ends_on date not null, active boolean not null default false,
  created_at timestamptz not null default now(), check(ends_on>=starts_on)
);

create index if not exists branches_institution_idx on public.branches(institution_id);
create index if not exists profiles_institution_idx on public.profiles(institution_id);
create index if not exists user_roles_role_idx on public.user_roles(role_id);
create index if not exists role_permissions_permission_idx on public.role_permissions(permission_id);
create index if not exists user_branches_branch_idx on public.user_branches(branch_id);
create index if not exists audit_logs_institution_created_idx on public.audit_logs(institution_id,created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql security invoker set search_path=public
as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists institutions_touch on public.institutions; create trigger institutions_touch before update on public.institutions for each row execute function public.touch_updated_at();
drop trigger if exists branches_touch on public.branches; create trigger branches_touch before update on public.branches for each row execute function public.touch_updated_at();
drop trigger if exists profiles_touch on public.profiles; create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
drop trigger if exists roles_touch on public.roles; create trigger roles_touch before update on public.roles for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public
as $$ begin insert into public.profiles(id,display_name) values(new.id,nullif(new.raw_user_meta_data->>'display_name','')) on conflict(id) do nothing; return new; end $$;
revoke all on function public.handle_new_user() from public,anon,authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function app_private.is_super_admin(uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,app_private
as $$ select exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=uid and r.slug='super-admin'); $$;
create or replace function app_private.has_permission(permission_key text,uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,app_private
as $$ select app_private.is_super_admin(uid) or exists(select 1 from public.user_roles ur join public.role_permissions rp on rp.role_id=ur.role_id join public.permissions p on p.id=rp.permission_id where ur.user_id=uid and p.key=permission_key); $$;
create or replace function app_private.has_branch_access(target_branch uuid,uid uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,app_private
as $$ select app_private.is_super_admin(uid) or exists(select 1 from public.user_branches ub where ub.user_id=uid and ub.branch_id=target_branch); $$;
revoke all on function app_private.is_super_admin(uuid) from public; revoke all on function app_private.has_permission(text,uuid) from public; revoke all on function app_private.has_branch_access(uuid,uuid) from public;
grant execute on function app_private.is_super_admin(uuid) to authenticated; grant execute on function app_private.has_permission(text,uuid) to authenticated; grant execute on function app_private.has_branch_access(uuid,uuid) to authenticated;

alter table public.institutions enable row level security; alter table public.branches enable row level security; alter table public.profiles enable row level security;
alter table public.roles enable row level security; alter table public.permissions enable row level security; alter table public.role_permissions enable row level security;
alter table public.user_roles enable row level security; alter table public.user_branches enable row level security; alter table public.app_settings enable row level security;
alter table public.audit_logs enable row level security; alter table public.academic_years enable row level security;

drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select to authenticated using(id=auth.uid() or app_private.is_super_admin());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update to authenticated using(id=auth.uid() or app_private.is_super_admin()) with check(id=auth.uid() or app_private.is_super_admin());
drop policy if exists institutions_admin on public.institutions;
create policy institutions_admin on public.institutions for all to authenticated using(app_private.is_super_admin()) with check(app_private.is_super_admin());
drop policy if exists branches_access on public.branches;
create policy branches_access on public.branches for select to authenticated using(app_private.is_super_admin() or app_private.has_branch_access(id));
create policy branches_admin on public.branches for all to authenticated using(app_private.is_super_admin()) with check(app_private.is_super_admin());
drop policy if exists roles_access on public.roles;
create policy roles_access on public.roles for select to authenticated using(app_private.is_super_admin() or app_private.has_permission('roles.view'));
create policy roles_admin on public.roles for all to authenticated using(app_private.is_super_admin() or app_private.has_permission('roles.edit')) with check(app_private.is_super_admin() or app_private.has_permission('roles.edit'));
drop policy if exists permissions_access on public.permissions;
create policy permissions_access on public.permissions for select to authenticated using(app_private.is_super_admin() or app_private.has_permission('roles.view'));
drop policy if exists role_permissions_access on public.role_permissions;
create policy role_permissions_access on public.role_permissions for all to authenticated using(app_private.is_super_admin() or app_private.has_permission('roles.edit')) with check(app_private.is_super_admin() or app_private.has_permission('roles.edit'));
drop policy if exists user_roles_access on public.user_roles;
create policy user_roles_access on public.user_roles for all to authenticated using(app_private.is_super_admin() or app_private.has_permission('roles.edit')) with check(app_private.is_super_admin() or app_private.has_permission('roles.edit'));
drop policy if exists user_branches_access on public.user_branches;
create policy user_branches_access on public.user_branches for all to authenticated using(app_private.is_super_admin() or app_private.has_permission('users.edit')) with check(app_private.is_super_admin() or app_private.has_permission('users.edit'));
drop policy if exists app_settings_access on public.app_settings;
create policy app_settings_access on public.app_settings for all to authenticated using(app_private.is_super_admin() or app_private.has_permission('settings.view')) with check(app_private.is_super_admin() or app_private.has_permission('settings.edit'));
drop policy if exists audit_logs_access on public.audit_logs;
create policy audit_logs_access on public.audit_logs for select to authenticated using(app_private.is_super_admin() or app_private.has_permission('audit.view'));
drop policy if exists audit_logs_insert on public.audit_logs;
create policy audit_logs_insert on public.audit_logs for insert to authenticated with check(actor_user_id=auth.uid());
drop policy if exists academic_years_access on public.academic_years;
create policy academic_years_access on public.academic_years for select to authenticated using(app_private.is_super_admin() or app_private.has_permission('academics.view'));
create policy academic_years_admin on public.academic_years for all to authenticated using(app_private.is_super_admin() or app_private.has_permission('academics.edit')) with check(app_private.is_super_admin() or app_private.has_permission('academics.edit'));

insert into public.permissions(key,description,module) values
('dashboard.view','View dashboard','dashboard'),('users.view','View users','users'),('users.create','Create users','users'),('users.edit','Edit users','users'),('users.disable','Disable users','users'),
('roles.view','View roles and permissions','security'),('roles.create','Create roles','security'),('roles.edit','Edit roles and permissions','security'),('roles.delete','Delete custom roles','security'),
('students.view','View students','students'),('students.create','Create students','students'),('students.edit','Edit students','students'),('students.archive','Archive students','students'),('students.delete','Delete students','students'),('students.export','Export students','students'),
('teachers.view','View teachers','teachers'),('teachers.create','Create teachers','teachers'),('teachers.edit','Edit teachers','teachers'),('teachers.delete','Delete teachers','teachers'),
('attendance.view','View attendance','attendance'),('attendance.create','Record attendance','attendance'),('attendance.edit','Edit attendance','attendance'),('attendance.delete','Delete attendance','attendance'),
('fees.view','View fees','fees'),('fees.create','Create fees','fees'),('fees.edit','Edit fees','fees'),('fees.delete','Delete fees','fees'),('fees.refund','Refund fees','fees'),
('finance.view','View finance','finance'),('finance.create','Create finance entries','finance'),('finance.edit','Edit finance entries','finance'),('finance.delete','Delete finance entries','finance'),('finance.export','Export finance','finance'),
('academics.view','View academics','academics'),('academics.edit','Manage academics','academics'),('settings.view','View settings','settings'),('settings.edit','Edit settings','settings'),
('reports.view','View reports','reports'),('reports.create','Build reports','reports'),('reports.export','Export reports','reports'),('audit.view','View audit logs','security')
on conflict(key) do update set description=excluded.description,module=excluded.module;

insert into public.roles(institution_id,name,slug,description,is_system)
select null,v.name,v.slug,v.description,true from (values
('Super Admin','super-admin','Full system control'),('Admin','admin','Administrative operations'),('Teacher / Ustad','teacher','Teaching operations'),('Staff','staff','General staff operations'),
('Student','student','Student portal access'),('Parent','parent','Parent portal access'),('Accountant','accountant','Fees and finance operations'),('HR','hr','Human resources operations'),
('Warden','warden','Hostel operations'),('Librarian','librarian','Library operations'),('Storekeeper','storekeeper','Inventory operations')) v(name,slug,description)
where not exists(select 1 from public.roles r where r.institution_id is null and r.slug=v.slug);

insert into public.role_permissions(role_id,permission_id)
select r.id,p.id from public.roles r cross join public.permissions p
where r.slug='super-admin' and r.institution_id is null on conflict do nothing;