-- Harden default role permissions and document payroll/promotion invariants.
-- Super Admin receives every defined permission; HR receives the complete HR permission set.
insert into public.role_permissions(role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.name = 'Super Admin'
on conflict do nothing;

insert into public.role_permissions(role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.name = 'HR'
  and p.key in ('hr.view','hr.create','hr.edit','hr.delete')
on conflict do nothing;

-- Promotion already has a unique (student_id, academic_year_id) constraint.
-- Payroll net_pay is generated by the existing table definition; no client-side
-- calculation is required for persistence.
