-- Phase 1+2 production foundation and student/academic hardening
create table if not exists public.campuses (
 id uuid primary key default gen_random_uuid(),
 institution_id uuid not null references public.institutions(id) on delete cascade,
 branch_id uuid references public.branches(id) on delete set null,
 name text not null,
 code text not null,
 address jsonb not null default '{}'::jsonb,
 active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(institution_id,code)
);
create table if not exists public.buildings (
 id uuid primary key default gen_random_uuid(),
 institution_id uuid not null references public.institutions(id) on delete cascade,
 campus_id uuid references public.campuses(id) on delete set null,
 name text not null,
 code text not null,
 floors integer not null default 1 check(floors>0),
 active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(institution_id,code)
);
create table if not exists public.departments (
 id uuid primary key default gen_random_uuid(),
 institution_id uuid not null references public.institutions(id) on delete cascade,
 name text not null,
 code text not null,
 active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(institution_id,code)
);
create table if not exists public.org_units (
 id uuid primary key default gen_random_uuid(),
 institution_id uuid not null references public.institutions(id) on delete cascade,
 parent_id uuid references public.org_units(id) on delete set null,
 department_id uuid references public.departments(id) on delete set null,
 name text not null,
 unit_type text not null default 'unit',
 active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.academic_terms (
 id uuid primary key default gen_random_uuid(),
 institution_id uuid not null references public.institutions(id) on delete cascade,
 academic_year_id uuid not null references public.academic_years(id) on delete cascade,
 name text not null,
 code text not null,
 starts_on date not null,
 ends_on date not null,
 active boolean not null default false,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(academic_year_id,code),
 check(ends_on>=starts_on)
);
create table if not exists public.login_events (
 id bigint generated by default as identity primary key,
 institution_id uuid references public.institutions(id) on delete set null,
 user_id uuid not null references auth.users(id) on delete cascade,
 event_type text not null check(event_type in ('login','logout','login_failed','password_reset','mfa_enrolled','mfa_removed')),
 ip_address inet,
 user_agent text,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
alter table public.students add column if not exists branch_id uuid references public.branches(id) on delete set null;
alter table public.students add column if not exists academic_year_id uuid references public.academic_years(id) on delete set null;
alter table public.students add column if not exists class_id uuid references public.academic_classes(id) on delete set null;
alter table public.students add column if not exists section_id uuid references public.sections(id) on delete set null;
alter table public.students add column if not exists student_type text not null default 'day_scholar' check(student_type in ('day_scholar','residential'));
alter table public.students add column if not exists arabic_name text;
alter table public.students add column if not exists urdu_name text;
alter table public.students add column if not exists emergency_contact jsonb not null default '{}'::jsonb;
alter table public.students add column if not exists previous_education jsonb not null default '{}'::jsonb;
alter table public.students add column if not exists custom_fields jsonb not null default '{}'::jsonb;
alter table public.students add column if not exists tags text[] not null default '{}';
alter table public.students add column if not exists accommodation_status text not null default 'day_scholar';
alter table public.students add column if not exists admission_source text;
alter table public.students add column if not exists completed_on date;
alter table public.students add column if not exists suspended_on date;
alter table public.admissions add column if not exists branch_id uuid references public.branches(id) on delete set null;
alter table public.admissions add column if not exists reviewed_remarks text;
alter table public.admissions add column if not exists converted_on date;
create index if not exists campuses_institution_idx on public.campuses(institution_id);
create index if not exists buildings_institution_idx on public.buildings(institution_id);
create index if not exists departments_institution_idx on public.departments(institution_id);
create index if not exists org_units_institution_idx on public.org_units(institution_id);
create index if not exists academic_terms_year_idx on public.academic_terms(academic_year_id);
create index if not exists login_events_user_created_idx on public.login_events(user_id,created_at desc);
create index if not exists students_class_section_idx on public.students(class_id,section_id);
create index if not exists students_branch_idx on public.students(branch_id);
alter table public.campuses enable row level security;
alter table public.buildings enable row level security;
alter table public.departments enable row level security;
alter table public.org_units enable row level security;
alter table public.academic_terms enable row level security;
alter table public.login_events enable row level security;
create or replace function app_private.same_institution(target_institution uuid) returns boolean language sql stable security definer set search_path=public,app_private as $$ select app_private.is_super_admin() or target_institution=(select institution_id from public.profiles where id=(select auth.uid())); $$;
revoke all on function app_private.same_institution(uuid) from public,anon;
grant execute on function app_private.same_institution(uuid) to authenticated;
drop policy if exists campuses_select on public.campuses;
drop policy if exists campuses_write on public.campuses;
create policy campuses_select on public.campuses for select to authenticated using(app_private.same_institution(institution_id) and app_private.has_permission('settings.view'));
create policy campuses_write on public.campuses for all to authenticated using(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('settings.edit'))) with check(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('settings.edit')));
drop policy if exists buildings_select on public.buildings;
drop policy if exists buildings_write on public.buildings;
create policy buildings_select on public.buildings for select to authenticated using(app_private.same_institution(institution_id) and app_private.has_permission('settings.view'));
create policy buildings_write on public.buildings for all to authenticated using(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('settings.edit'))) with check(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('settings.edit')));
drop policy if exists departments_select on public.departments;
drop policy if exists departments_write on public.departments;
create policy departments_select on public.departments for select to authenticated using(app_private.same_institution(institution_id) and app_private.has_permission('settings.view'));
create policy departments_write on public.departments for all to authenticated using(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('settings.edit'))) with check(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('settings.edit')));
drop policy if exists org_units_select on public.org_units;
drop policy if exists org_units_write on public.org_units;
create policy org_units_select on public.org_units for select to authenticated using(app_private.same_institution(institution_id) and app_private.has_permission('settings.view'));
create policy org_units_write on public.org_units for all to authenticated using(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('settings.edit'))) with check(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('settings.edit')));
drop policy if exists academic_terms_select on public.academic_terms;
drop policy if exists academic_terms_write on public.academic_terms;
create policy academic_terms_select on public.academic_terms for select to authenticated using(app_private.same_institution(institution_id) and app_private.has_permission('academics.view'));
create policy academic_terms_write on public.academic_terms for all to authenticated using(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('academics.edit'))) with check(app_private.is_super_admin() or (app_private.same_institution(institution_id) and app_private.has_permission('academics.edit')));
create policy login_events_select on public.login_events for select to authenticated using(app_private.is_super_admin() or (user_id=auth.uid()) or app_private.has_permission('audit.view'));
create policy login_events_insert on public.login_events for insert to authenticated with check(user_id=auth.uid() or app_private.is_super_admin());
create trigger campuses_touch before update on public.campuses for each row execute function public.touch_updated_at();
create trigger buildings_touch before update on public.buildings for each row execute function public.touch_updated_at();
create trigger departments_touch before update on public.departments for each row execute function public.touch_updated_at();
create trigger org_units_touch before update on public.org_units for each row execute function public.touch_updated_at();
create trigger academic_terms_touch before update on public.academic_terms for each row execute function public.touch_updated_at();
grant select,insert,update,delete on public.campuses,public.buildings,public.departments,public.org_units,public.academic_terms,public.login_events to authenticated;
insert into public.permissions(key,description,module) values
('settings.view','View institution settings','settings'),
('settings.edit','Manage institution structure and settings','settings'),
('students.create','Create students','students'),
('students.edit','Edit students','students'),
('students.delete','Delete students','students'),
('students.export','Export students','students'),
('academics.view','View academics','academics'),
('academics.edit','Manage academics','academics'),
('audit.view','View audit and security events','security')
on conflict(key) do update set description=excluded.description,module=excluded.module;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.slug='super-admin' and r.institution_id is null on conflict do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.key in ('settings.view','settings.edit','academics.view','academics.edit','students.view','students.create','students.edit','students.delete','students.export') where r.slug='admin' on conflict do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.key in ('academics.view','students.view') where r.slug in ('teacher','hr','warden','librarian','accountant','staff') on conflict do nothing;
create or replace function public.admission_review(target_admission uuid,target_status text,target_remarks text default null)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare a public.admissions%rowtype;
begin
 if target_status not in ('pending','approved','rejected','waitlisted','cancelled','converted') then raise exception 'Invalid admission status'; end if;
 select * into a from public.admissions where id=target_admission for update;
 if not found then raise exception 'Admission not found'; end if;
 if not app_private.is_super_admin() and not app_private.has_permission('students.edit') then raise exception 'Not authorized'; end if;
 if not app_private.same_institution(a.institution_id) then raise exception 'Institution mismatch'; end if;
 update public.admissions set status=target_status,reviewed_by=auth.uid(),reviewed_at=now(),reviewed_remarks=target_remarks,updated_at=now() where id=target_admission;
 insert into public.audit_logs(institution_id,actor_user_id,action,entity_type,entity_id,metadata) values(a.institution_id,auth.uid(),'admission.status_changed','admission',a.id::text,jsonb_build_object('from',a.status,'to',target_status));
 return jsonb_build_object('id',a.id,'status',target_status);
end $$;
revoke all on function public.admission_review(uuid,text,text) from public,anon;
grant execute on function public.admission_review(uuid,text,text) to authenticated;
create or replace function public.enroll_student(target_student uuid,target_year uuid,target_class uuid,target_section uuid default null,target_roll_no text default null)
returns uuid language plpgsql security invoker set search_path=public as $$
declare sid uuid; inst uuid;
begin
 select institution_id into inst from public.students where id=target_student;
 if inst is null then raise exception 'Student not found'; end if;
 if not (app_private.is_super_admin() or app_private.has_permission('students.create')) then raise exception 'Not authorized'; end if;
 if not app_private.same_institution(inst) then raise exception 'Institution mismatch'; end if;
 insert into public.student_enrollments(institution_id,student_id,academic_year_id,class_id,section_id,roll_no,status) values(inst,target_student,target_year,target_class,target_section,target_roll_no,'active') returning id into sid;
 update public.students set academic_year_id=target_year,class_id=target_class,section_id=target_section,roll_no=target_roll_no,status='active' where id=target_student;
 insert into public.audit_logs(institution_id,actor_user_id,action,entity_type,entity_id,metadata) values(inst,auth.uid(),'student.enrolled','student',target_student::text,jsonb_build_object('academic_year_id',target_year,'class_id',target_class,'section_id',target_section));
 return sid;
end $$;
revoke all on function public.enroll_student(uuid,uuid,uuid,uuid,text) from public,anon;
grant execute on function public.enroll_student(uuid,uuid,uuid,uuid,text) to authenticated;